version: '2'

services:
  mysql:
    image: mysql:5.7
    container_name: mymysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      # MYSQL_ROOT_HOST: '%'
    restart: always
    volumes:
      - './db:/var/lib/mysql'
      - './init:/docker-entrypoint-initdb.d/'
      - './conf:/etc/mysql'
