version: '3'

services:
  mymysql:
    image: mysql:5.7
    container_name: mymysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_ROOT_HOST: '%'
    restart: always
    build:
      context: ./mysql
      dockerfile: Dockerfile
    volumes:
      - './mysql/my.cnf:/etc/my.cnf'
