FROM java:8
EXPOSE 8080
VOLUME /slm
ADD docker.jar docker.jar
RUN sh -c 'touch /docker.jar'
ENV JAVA_OPTS=""
ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /docker.jar" ]
